# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2.2'

volumes:
  orderer.example.com:
  peer0.org1.example.com:
  peer0.org2.example.com:
# networks:
#   byfn:

services:
  orderer.example.com:
    extends:
      file: base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    # networks:
    #   - byfn

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.org1.example.com
    # networks:
    #   - byfn
  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.org2.example.com
    # networks:
    #   - byfn
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.example.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6080d464ac5e06f737a52b0ef533ce1ed69c2ddda33056173a875cebba707e49_sk
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/54632c429c67d733521952792ddb2804a9cda6abf1652860159f8439c2860fa5_sk
    ports:
      - '7054:7054'
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/6080d464ac5e06f737a52b0ef533ce1ed69c2ddda33056173a875cebba707e49_sk -b admin:adminpw -d'
    # command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/54632c429c67d733521952792ddb2804a9cda6abf1652860159f8439c2860fa5_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/ordererOrganizations/example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    # networks:
    #   - byfn
    depends_on:
      - orderer.example.com
      - peer0.org1.example.com
      - peer0.org2.example.com
